export enum ROLES {
    SYSTEM_ADMINISTRATOR = "SYSTEM_ADMINISTRATOR",
    EXTERNAL_MAINTENANCE_COMPANY = "EXTERNAL_MAINTENANCE_COMPANY",
    HEADQUARTERS_MANAGEMENT_DEPARTMENT = "HEADQUARTERS_MANAGEMENT_DEPARTMENT",
    WAREHOUSE_MANAGER = "WAREHOUSE_MANAGER",
    MAINTENANCE_STAFF = "MAINTENANCE_STAFF",
    DRIVER = "DRIVER"
}
